# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f252e5e1ef5d7d90173fb71b4785da2342cb9049cfbafc55f1585448e591547a0864104ce1556e753df542575c17de9fddacbdb5eff2693d80961bf63220134f
email_provider_username: copernicus74@hotmail.com
mailchimp_api_key:
mailchimp_list_id:
domain_name:
owner_email:


test:
  secret_key_base: 5e740d94816012421a03e688c749981a89d86dd43d45c72fcd7b283b8b9285bd169bac5b1555f3e04f831a7dde7a55168af64fb41e626acfe29b6437e1b354ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
